### ISSUE TITLE
Error even with yarn install workaround

### ISSUE THREAD

**Issue by chronos-ohm** [Snazzah/slash-create-vercel#1]
I have set the install command as mentioned in the README `yarn config set ignore-engines true && yarn install --network-concurrency 1`

The first deployment works, although the subsequent ones always fail with this. Still haven't found the cause. Any clues? Thanks!
![image](https://user-images.githubusercontent.com/93824165/154340757-c5d30da4-db23-4260-82eb-438d1b8e3b49.png)

**Comment by Snazzah** [comment]
Was this already solved? You should make sure to update slash-create to the latest version.
